# docker-compose.build.yml
x-service-template: &catalog-service
  build:
    context: .
    dockerfile: Dockerfile
    args:
      NEXT_PUBLIC_APP_VERSION: ${NEXT_PUBLIC_APP_VERSION}
      NEXT_PUBLIC_APP_COMMIT: ${NEXT_PUBLIC_APP_COMMIT}

services:
  sysintegra-services:
    <<: *catalog-service
    image: sysintegra-catalog

  leatsac-services:
    <<: *catalog-service
    image: leatsac-catalog

  importmuneli-services:
    <<: *catalog-service
    image: importmuneli-catalog