# deploy/config.yml

# branchs:
  # test
  # production
  # preview

repositories: syssoftintegra/catalog

clients:

  sysintegra:
    service: sysintegra-services
    deploy: test

  leatsac:
    service: leatsac-services
    deploy: production

  importmuneli:
    service: importmuneli-services
    deploy: preview